// Code generated by BobGen psql v0.28.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/im"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// Item is an object representing the database table.
type Item struct {
	ID                string              `db:"id,pk" json:"id"`
	UserID            string              `db:"user_id" json:"userId"`
	Type              string              `db:"type" json:"type"`
	ParentID          null.Val[string]    `db:"parent_id" json:"parentId"`
	Name              string              `db:"name" json:"name"`
	Content           string              `db:"content" json:"content"`
	SortKey           string              `db:"sort_key" json:"sortKey"`
	Version           int64               `db:"version" json:"version"`
	DeviceID          string              `db:"device_id" json:"deviceId"`
	LastSyncedVersion int64               `db:"last_synced_version" json:"lastSyncedVersion"`
	DeletedAt         null.Val[time.Time] `db:"deleted_at" json:"deletedAt"`
	CreatedAt         time.Time           `db:"created_at" json:"createdAt"`
	UpdatedAt         time.Time           `db:"updated_at" json:"updatedAt"`
}

// ItemSlice is an alias for a slice of pointers to Item.
// This should almost always be used instead of []*Item.
type ItemSlice []*Item

// Items contains methods to work with the items table
var Items = psql.NewTablex[*Item, ItemSlice, *ItemSetter]("", "items")

// ItemsQuery is a query on the items table
type ItemsQuery = *psql.ViewQuery[*Item, ItemSlice]

// ItemsStmt is a prepared statment on items
type ItemsStmt = bob.QueryStmt[*Item, ItemSlice]

// ItemSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ItemSetter struct {
	ID                omit.Val[string]        `db:"id,pk" json:"id"`
	UserID            omit.Val[string]        `db:"user_id" json:"userId"`
	Type              omit.Val[string]        `db:"type" json:"type"`
	ParentID          omitnull.Val[string]    `db:"parent_id" json:"parentId"`
	Name              omit.Val[string]        `db:"name" json:"name"`
	Content           omit.Val[string]        `db:"content" json:"content"`
	SortKey           omit.Val[string]        `db:"sort_key" json:"sortKey"`
	Version           omit.Val[int64]         `db:"version" json:"version"`
	DeviceID          omit.Val[string]        `db:"device_id" json:"deviceId"`
	LastSyncedVersion omit.Val[int64]         `db:"last_synced_version" json:"lastSyncedVersion"`
	DeletedAt         omitnull.Val[time.Time] `db:"deleted_at" json:"deletedAt"`
	CreatedAt         omit.Val[time.Time]     `db:"created_at" json:"createdAt"`
	UpdatedAt         omit.Val[time.Time]     `db:"updated_at" json:"updatedAt"`
}

func (s ItemSetter) SetColumns() []string {
	vals := make([]string, 0, 13)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.UserID.IsUnset() {
		vals = append(vals, "user_id")
	}

	if !s.Type.IsUnset() {
		vals = append(vals, "type")
	}

	if !s.ParentID.IsUnset() {
		vals = append(vals, "parent_id")
	}

	if !s.Name.IsUnset() {
		vals = append(vals, "name")
	}

	if !s.Content.IsUnset() {
		vals = append(vals, "content")
	}

	if !s.SortKey.IsUnset() {
		vals = append(vals, "sort_key")
	}

	if !s.Version.IsUnset() {
		vals = append(vals, "version")
	}

	if !s.DeviceID.IsUnset() {
		vals = append(vals, "device_id")
	}

	if !s.LastSyncedVersion.IsUnset() {
		vals = append(vals, "last_synced_version")
	}

	if !s.DeletedAt.IsUnset() {
		vals = append(vals, "deleted_at")
	}

	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}

	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}

	return vals
}

func (s ItemSetter) Overwrite(t *Item) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.UserID.IsUnset() {
		t.UserID, _ = s.UserID.Get()
	}
	if !s.Type.IsUnset() {
		t.Type, _ = s.Type.Get()
	}
	if !s.ParentID.IsUnset() {
		t.ParentID, _ = s.ParentID.GetNull()
	}
	if !s.Name.IsUnset() {
		t.Name, _ = s.Name.Get()
	}
	if !s.Content.IsUnset() {
		t.Content, _ = s.Content.Get()
	}
	if !s.SortKey.IsUnset() {
		t.SortKey, _ = s.SortKey.Get()
	}
	if !s.Version.IsUnset() {
		t.Version, _ = s.Version.Get()
	}
	if !s.DeviceID.IsUnset() {
		t.DeviceID, _ = s.DeviceID.Get()
	}
	if !s.LastSyncedVersion.IsUnset() {
		t.LastSyncedVersion, _ = s.LastSyncedVersion.Get()
	}
	if !s.DeletedAt.IsUnset() {
		t.DeletedAt, _ = s.DeletedAt.GetNull()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt, _ = s.CreatedAt.Get()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt, _ = s.UpdatedAt.Get()
	}
}

func (s ItemSetter) InsertMod() bob.Mod[*dialect.InsertQuery] {
	vals := make([]bob.Expression, 13)
	if s.ID.IsUnset() {
		vals[0] = psql.Raw("DEFAULT")
	} else {
		vals[0] = psql.Arg(s.ID)
	}

	if s.UserID.IsUnset() {
		vals[1] = psql.Raw("DEFAULT")
	} else {
		vals[1] = psql.Arg(s.UserID)
	}

	if s.Type.IsUnset() {
		vals[2] = psql.Raw("DEFAULT")
	} else {
		vals[2] = psql.Arg(s.Type)
	}

	if s.ParentID.IsUnset() {
		vals[3] = psql.Raw("DEFAULT")
	} else {
		vals[3] = psql.Arg(s.ParentID)
	}

	if s.Name.IsUnset() {
		vals[4] = psql.Raw("DEFAULT")
	} else {
		vals[4] = psql.Arg(s.Name)
	}

	if s.Content.IsUnset() {
		vals[5] = psql.Raw("DEFAULT")
	} else {
		vals[5] = psql.Arg(s.Content)
	}

	if s.SortKey.IsUnset() {
		vals[6] = psql.Raw("DEFAULT")
	} else {
		vals[6] = psql.Arg(s.SortKey)
	}

	if s.Version.IsUnset() {
		vals[7] = psql.Raw("DEFAULT")
	} else {
		vals[7] = psql.Arg(s.Version)
	}

	if s.DeviceID.IsUnset() {
		vals[8] = psql.Raw("DEFAULT")
	} else {
		vals[8] = psql.Arg(s.DeviceID)
	}

	if s.LastSyncedVersion.IsUnset() {
		vals[9] = psql.Raw("DEFAULT")
	} else {
		vals[9] = psql.Arg(s.LastSyncedVersion)
	}

	if s.DeletedAt.IsUnset() {
		vals[10] = psql.Raw("DEFAULT")
	} else {
		vals[10] = psql.Arg(s.DeletedAt)
	}

	if s.CreatedAt.IsUnset() {
		vals[11] = psql.Raw("DEFAULT")
	} else {
		vals[11] = psql.Arg(s.CreatedAt)
	}

	if s.UpdatedAt.IsUnset() {
		vals[12] = psql.Raw("DEFAULT")
	} else {
		vals[12] = psql.Arg(s.UpdatedAt)
	}

	return im.Values(vals...)
}

func (s ItemSetter) Apply(q *dialect.UpdateQuery) {
	um.Set(s.Expressions()...).Apply(q)
}

func (s ItemSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 13)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if !s.UserID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if !s.Type.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "type")...),
			psql.Arg(s.Type),
		}})
	}

	if !s.ParentID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "parent_id")...),
			psql.Arg(s.ParentID),
		}})
	}

	if !s.Name.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if !s.Content.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "content")...),
			psql.Arg(s.Content),
		}})
	}

	if !s.SortKey.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "sort_key")...),
			psql.Arg(s.SortKey),
		}})
	}

	if !s.Version.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "version")...),
			psql.Arg(s.Version),
		}})
	}

	if !s.DeviceID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "device_id")...),
			psql.Arg(s.DeviceID),
		}})
	}

	if !s.LastSyncedVersion.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "last_synced_version")...),
			psql.Arg(s.LastSyncedVersion),
		}})
	}

	if !s.DeletedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "deleted_at")...),
			psql.Arg(s.DeletedAt),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

type itemColumnNames struct {
	ID                string
	UserID            string
	Type              string
	ParentID          string
	Name              string
	Content           string
	SortKey           string
	Version           string
	DeviceID          string
	LastSyncedVersion string
	DeletedAt         string
	CreatedAt         string
	UpdatedAt         string
}

var ItemColumns = buildItemColumns("items")

type itemColumns struct {
	tableAlias        string
	ID                psql.Expression
	UserID            psql.Expression
	Type              psql.Expression
	ParentID          psql.Expression
	Name              psql.Expression
	Content           psql.Expression
	SortKey           psql.Expression
	Version           psql.Expression
	DeviceID          psql.Expression
	LastSyncedVersion psql.Expression
	DeletedAt         psql.Expression
	CreatedAt         psql.Expression
	UpdatedAt         psql.Expression
}

func (c itemColumns) Alias() string {
	return c.tableAlias
}

func (itemColumns) AliasedAs(alias string) itemColumns {
	return buildItemColumns(alias)
}

func buildItemColumns(alias string) itemColumns {
	return itemColumns{
		tableAlias:        alias,
		ID:                psql.Quote(alias, "id"),
		UserID:            psql.Quote(alias, "user_id"),
		Type:              psql.Quote(alias, "type"),
		ParentID:          psql.Quote(alias, "parent_id"),
		Name:              psql.Quote(alias, "name"),
		Content:           psql.Quote(alias, "content"),
		SortKey:           psql.Quote(alias, "sort_key"),
		Version:           psql.Quote(alias, "version"),
		DeviceID:          psql.Quote(alias, "device_id"),
		LastSyncedVersion: psql.Quote(alias, "last_synced_version"),
		DeletedAt:         psql.Quote(alias, "deleted_at"),
		CreatedAt:         psql.Quote(alias, "created_at"),
		UpdatedAt:         psql.Quote(alias, "updated_at"),
	}
}

type itemWhere[Q psql.Filterable] struct {
	ID                psql.WhereMod[Q, string]
	UserID            psql.WhereMod[Q, string]
	Type              psql.WhereMod[Q, string]
	ParentID          psql.WhereNullMod[Q, string]
	Name              psql.WhereMod[Q, string]
	Content           psql.WhereMod[Q, string]
	SortKey           psql.WhereMod[Q, string]
	Version           psql.WhereMod[Q, int64]
	DeviceID          psql.WhereMod[Q, string]
	LastSyncedVersion psql.WhereMod[Q, int64]
	DeletedAt         psql.WhereNullMod[Q, time.Time]
	CreatedAt         psql.WhereMod[Q, time.Time]
	UpdatedAt         psql.WhereMod[Q, time.Time]
}

func (itemWhere[Q]) AliasedAs(alias string) itemWhere[Q] {
	return buildItemWhere[Q](buildItemColumns(alias))
}

func buildItemWhere[Q psql.Filterable](cols itemColumns) itemWhere[Q] {
	return itemWhere[Q]{
		ID:                psql.Where[Q, string](cols.ID),
		UserID:            psql.Where[Q, string](cols.UserID),
		Type:              psql.Where[Q, string](cols.Type),
		ParentID:          psql.WhereNull[Q, string](cols.ParentID),
		Name:              psql.Where[Q, string](cols.Name),
		Content:           psql.Where[Q, string](cols.Content),
		SortKey:           psql.Where[Q, string](cols.SortKey),
		Version:           psql.Where[Q, int64](cols.Version),
		DeviceID:          psql.Where[Q, string](cols.DeviceID),
		LastSyncedVersion: psql.Where[Q, int64](cols.LastSyncedVersion),
		DeletedAt:         psql.WhereNull[Q, time.Time](cols.DeletedAt),
		CreatedAt:         psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:         psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

// FindItem retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindItem(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Item, error) {
	if len(cols) == 0 {
		return Items.Query(
			ctx, exec,
			SelectWhere.Items.ID.EQ(IDPK),
		).One()
	}

	return Items.Query(
		ctx, exec,
		SelectWhere.Items.ID.EQ(IDPK),
		sm.Columns(Items.Columns().Only(cols...)),
	).One()
}

// ItemExists checks the presence of a single record by primary key
func ItemExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Items.Query(
		ctx, exec,
		SelectWhere.Items.ID.EQ(IDPK),
	).Exists()
}

// PrimaryKeyVals returns the primary key values of the Item
func (o *Item) PrimaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

// Update uses an executor to update the Item
func (o *Item) Update(ctx context.Context, exec bob.Executor, s *ItemSetter) error {
	return Items.Update(ctx, exec, s, o)
}

// Delete deletes a single Item record with an executor
func (o *Item) Delete(ctx context.Context, exec bob.Executor) error {
	return Items.Delete(ctx, exec, o)
}

// Reload refreshes the Item using the executor
func (o *Item) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Items.Query(
		ctx, exec,
		SelectWhere.Items.ID.EQ(o.ID),
	).One()
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

func (o ItemSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ItemSetter) error {
	return Items.Update(ctx, exec, &vals, o...)
}

func (o ItemSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	return Items.Delete(ctx, exec, o...)
}

func (o ItemSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	var mods []bob.Mod[*dialect.SelectQuery]

	IDPK := make([]string, len(o))

	for i, o := range o {
		IDPK[i] = o.ID
	}

	mods = append(mods,
		SelectWhere.Items.ID.In(IDPK...),
	)

	o2, err := Items.Query(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, old := range o {
		for _, new := range o2 {
			if new.ID != old.ID {
				continue
			}

			*old = *new
			break
		}
	}

	return nil
}
